# Generated by Django 3.0.4 on 2020-03-23 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Subscriber')),
            ],
        ),
    ]
