# Generated by Django 3.0.4 on 2020-03-23 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
